export const SET_CURRENET_INTERVIEW_SECTION = "SET_CURRENET_INTERVIEW_SECTION";
export const SET_CURRENET_INTERVIEW_FUNCTIONALITY =
  "SET_CURRENET_INTERVIEW_FUNCTIONALITY";
export const SET_LOADING = "SET_LOADING";
