export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const GET_USER_DATA = "GET_USER_DATA";
export const SET_AUTHORIZATION_MANUALLY = "SET_AUTHORIZATION_MANUALLY";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
